add tests for the node resize feature and properties of Group and text Annotation
ljmotta/kie-tools pull request #27
Opened 2024-03-28 12:09 UTC by jomarko

This depends on changes from the #26 

As part of this PR we add:
- Tests of the resize feature. We select node, using its `resize-handle` element we increase its size and then we check the size property in the properties panel
- Add missing tests of #26, where we missed to check properties panel for `Group` and `text Annotation` nodes

2024-04-02 14:55 UTC, jomarko commented on packages/dmn-editor/src/propertiesPanel/FontOptions.tsx
> +            </div>
We can not simply add `data-testid` int `Select`, patternfly for some reason ignores that attribute.

2024-04-05 23:11 UTC, ljmotta requested changes
Alright, the tests are looking good, but it's still missing a few ones. Some of them I've added inline on the test files. We also need to test the documentation links with more cases. Add one more and change orders, for example. We also need to test the reset style button, for now, we can only test with the node font. The documentation links can be added to a different file, as it's not node specific.

Great job on the resize tests. But they are missing a few cases too:
 - Resize with the snapping on?
 - Change the snapping values?
 - Resize on top of another node?

Now, regarding the fixtures, I don't think they're looking good. The class inheritance doesn't fit in some cases, making it necessary to add `throw new Error` methods. The way to solve this is with class composition. Instead of inheritance, we pass the instance or create the instance on the constructor and attribute it to one property. This way the class will have only the necessary methods. Also, I don't think this would be good either. We can't be sure the nodes will always share those properties, and maybe the best way is to replicate the logic on each class, removing the coupling altogether. Duplicating the code isn't a bad thing in this case, as it'll remove the complexity of creating the abstraction.

2024-04-08 07:42 UTC, jomarko commented on packages/dmn-editor/src/propertiesPanel/FontOptions.tsx
> +            </div>
Probably we can not, `<React.Fragment data-testid={"xyz"}>` has no effect for the produced html.  The `data-testid` is not in the generated html at all.

2024-04-08 07:50 UTC, jomarko commented on packages/dmn-editor/tests/e2e/drgElements/changeMultipleNodesProperties.spec.ts
moved one level up

2024-04-08 07:53 UTC, jomarko commented on packages/dmn-editor/tests/e2e/drgElements/changeMultipleNodesProperties.spec.ts
Sorry, I do not get it, as I tried to explain, I am not able to write a test for a color change using playwright. Could you please help me and advise how to write such a test? I am not able to handle the color picker we use in KIE tooling.

2024-04-08 08:25 UTC, jomarko commented on packages/dmn-editor/tests/e2e/drgElements/changeDiagramProperties.spec.ts
tests added

2024-04-08 08:27 UTC, jomarko commented on packages/dmn-editor/tests/e2e/drgElements/changeDecisionServiceProperties.spec.ts
I agree we need such tests, will add them as part of https://github.com/ljmotta/kie-tools/pull/29

2024-04-15 12:56 UTC, jomarko commented
replaced by https://github.com/apache/incubator-kie-tools/pull/2239

2024-04-15 12:56 UTC, closed without merging